
set  -g default-terminal "screen"
set  -g base-index      1
setw -g pane-base-index 1





set -g status-keys emacs
set -g mode-keys   emacs



# rebind main key: M-x
unbind C-b
set -g prefix M-x
bind -N "Send the prefix key through to the application" \
  M-x send-prefix




set  -g mouse             on
set  -g focus-events      off
setw -g aggressive-resize off
setw -g clock-mode-style  12
set  -s escape-time       10
set  -g history-limit     2000

# ============================================= #
# Load plugins with Home Manager                #
# --------------------------------------------- #

# tmuxplugin-gruvbox
# ---------------------

run-shell /nix/store/6qx8x17s2mj864iy7995gxjn89i65q0y-tmuxplugin-gruvbox-2.0.1/share/tmux-plugins/gruvbox/gruvbox-tpm.tmux

# ============================================= #

set -g status-position top
set -g status-right ""
