# Terminal / Shell
set -g default-terminal "screen-256color"
set -g default-shell /usr/bin/zsh

# Index starts at 1
set -g base-index 1
setw -g pane-base-index 1

# Keys
set -g status-keys emacs
set -g mode-keys vi

# Vim copy mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Prefix: M-x
unbind C-b
set -g prefix M-x

bind -N "Send the prefix key through to the application" \
    M-x send-prefix

# General
set -g mouse on
set -g focus-events off
setw -g aggressive-resize off
setw -g clock-mode-style 12
set -s escape-time 10
set -g history-limit 2000

# -------------------------
# Plugins
# -------------------------

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'egel/tmux-gruvbox'

# Gruvbox
set -g @tmux-gruvbox 'dark'
run-shell ~/.tmux/plugins/tmux-gruvbox/gruvbox-tpm.tmux

# Status bar
set -g status-position top
set -g status-right ""
